name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Check current directory
        run: pwd
      - name: List directory contents
        run: ls -al
      - name: Run Feed Generator
        #run: cd subdirectory && python feed.py
        #run: python /workspaces/podcast-test/feed.py
        run: python /home/runner/work/podcast-test/podcast-test/feed.py
      - name: Push Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Modified Feed"
          git push
